# Generated by Django 2.2 on 2020-09-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_a_n', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
