# Generated by Django 2.2 on 2020-09-10 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m_a_n', '0002_shop_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='m_a_n.Shop'),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='creator',
        ),
        migrations.AddField(
            model_name='shop',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='m_a_n.User'),
        ),
    ]
