# Generated by Django 2.2 on 2020-09-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_a_n', '0009_auto_20200911_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
